src/SCP.Web/Controllers/BadController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SCP.Data;
using SCP.Data.Entities;
using SCP.Diagnostics.Logging;
using SCP.Web.Models;

namespace SCP.Web.Controllers
{
    public class BadController : Controller
    {
        private readonly ILogger _logger;
        private readonly ScpDbContext _context;

        public BadController(ILogger logger, ScpDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public ActionResult Index()
        {
            return View();
        }

        [ValidateInput(false)]
        public ActionResult InputValidation()
        {
            // QueryString Parameters Remembered by Browsers
            var name = Request.QueryString["name"];
            var ageTemp = Request.QueryString["age"];
            var age = string.IsNullOrEmpty(ageTemp) ? 0 : int.Parse(ageTemp);
            var notes = Request.QueryString["notes"];
            var model = new InputValidationModel(name, age, notes);
            return View(model);
        }

        public ActionResult OutputEncoding()
        {
            var model = new OutputEncodingModel();
            return View(model);
        }

        public ActionResult Authentication()
        {
            User user = null;
            var username = Request.QueryString["username"];
            var password = Request.QueryString["password"];
            if (!string.IsNullOrEmpty(username))
            {
                // ce0bfd15059b68d67688884d7a3d3e8c
                var query = "SELECT * FROM User WHERE username ='" + username + "' and password ='" + password + "'";
                user = _context.Users.SqlQuery(query).FirstOrDefault();
            }
            if (user == null) user = new User();
            return View(user);
        }

        private const string SessionCookieName = "obviously_session_id";

        public ActionResult SessionManagement()
        {
            var siteCookie = GetSessionCookie();
            if (siteCookie != null)
            {
                ViewData["session_id"] = siteCookie.Value;
                return View();
            }
            var rnd = new Random();
            var random = rnd.Next(0, 1000);
            var sessionId = (DateTime.Now.Ticks + random).ToString();
            var sessionCookie = new HttpCookie(SessionCookieName)
            {
                Value = sessionId
            };
            Response.Cookies.Add(sessionCookie);

            ViewData["session_id"] = sessionId;
            return View();
        }

        private HttpCookie GetSessionCookie()
        {
            if (Request.Cookies.AllKeys.Contains(SessionCookieName))
            {
                var cookie = Request.Cookies[SessionCookieName];
                return cookie;
            }
            return null;
        }

        public ActionResult SessionManagementLogout(bool logout)
        {
            if (logout)
            {
                Session.Abandon();
                ViewData["session_id"] = "good bye";
            }
            return RedirectToAction("SessionManagement");
        }

        private const string AccessLevel = "access_level";

        public ActionResult AccessControl(int userType = 0)
        {
            ViewData[AccessLevel] = "None";
            switch (userType)
            {
                case 1:
                    ViewData[AccessLevel] = "User";
                    break;
                case 2:
                    ViewData[AccessLevel] = "Staff";
                    break;
                case 3:
                    ViewData[AccessLevel] = "Admin";
                    break;
            }
            return View();
        }

        public ActionResult CryptographicPractices()
        {
            return View();
        }


        public ActionResult ErrorHandling(string someParameter = "")
        {
            Exception exception;
            try
            {
                throw new InvalidOperationException(string.Format("Invalid parameter {0}", someParameter));
            }
            catch (Exception ex)
            {
                exception = ex;
            }
            return View(exception);
        }

        public ActionResult Logging(string someSensitiveData = "")
        {
            try
            {
                throw new InvalidOperationException(string.Format("Invalid parameter {0}", someSensitiveData));
            }
            catch (Exception ex)
            {
                _logger.Error("Error Happend", ex);
            }
            return View();
        }

        public ActionResult DataProtection()
        {
            return View();
        }

        public ActionResult CommunicationSecurity()
        {
            return View();
        }

        [HttpGet]
        public ActionResult FileManagement()
        {
            return View();
        }

        [HttpPost]
        public ActionResult FileManagement(HttpPostedFileBase upload)
        {
            if (upload != null && upload.ContentLength > 0)
            {
                var fileName = Path.GetFileName(upload.FileName);
                var path = Path.Combine(Server.MapPath("~/uploads/"), fileName);
                upload.SaveAs(path);
            }
            return View();
        }

        public ActionResult MemoryManagement()
        {
            var fs = new FileInfo(Server.MapPath("~/App_Data/test.txt")).OpenRead();
            var sr = new StreamReader(fs);
            ViewData["data"] = sr.ReadToEnd();
            return View();
        }
    }
}

src/SCP.Web/Controllers/GoodController.cs
using System;
using System.IO;
using System.Linq;
using System.Net.Configuration;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using FileTypeDetective;
using SCP.Configuration;
using SCP.Data;
using SCP.Data.Entities;
using SCP.Diagnostics.Logging;
using SCP.Security;
using SCP.Security.Cryptography;
using SCP.Web.Models;

namespace SCP.Web.Controllers
{
    [AllowAnonymous]
    public class GoodController : Controller
    {
        private readonly ILogger _logger;
        private readonly ISettingsProvider _settingsProvider;
        private readonly IScpUnitOfWork _unitOfWork;
        private readonly IPasswordHashProvidcer _passwordHashProvidcer;
        private readonly IEncryptionProvider _encryptionProvider;
        private readonly IRandomNumberGenerator _randomNumberGenerator;
        private string _key;
        private string _vector;
        private string _salt;

        public GoodController(ILogger logger, ISettingsProvider settingsProvider, IScpUnitOfWork unitOfWork, IPasswordHashProvidcer passwordHashProvidcer, IEncryptionProvider encryptionProvider, IRandomNumberGenerator randomNumberGenerator)
        {
            _logger = logger;
            _settingsProvider = settingsProvider;
            _unitOfWork = unitOfWork;
            _passwordHashProvidcer = passwordHashProvidcer;
            _encryptionProvider = encryptionProvider;
            _randomNumberGenerator = randomNumberGenerator;

            _key = _settingsProvider.GetAppSetting(ConfigurationKeys.Key);
            _vector = _settingsProvider.GetAppSetting(ConfigurationKeys.Vector);
            _salt = _settingsProvider.GetAppSetting(ConfigurationKeys.Salt);
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult InputValidation()
        {
            return View(new InputValidationModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult InputValidation(InputValidationModel model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "Your inputs are not valid.");
                return View(new InputValidationModel());
            }
            return View(model);
        }

        public ActionResult OutputEncoding()
        {
            var model = new OutputEncodingModel();
            // Sanitize Path
            if (model.Path.Contains(HttpRuntime.AppDomainAppPath))
                model.Path = "~\\";
            // Sanitize Credit Card Number
            var first4 = model.CreditCardNumber.Substring(0, 4);
            var last4 = model.CreditCardNumber.Substring(model.CreditCardNumber.Length - 4, 4);
            model.CreditCardNumber = first4 + " **** **** " + last4;
            return View(model);
        }

        [HttpGet]
        public ActionResult Authentication()
        {
            var model = new AuthenticationViewModel();
            return View(model);
        }

        private const string SessionUserKey = "User";
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Authentication(AuthenticationPostModel postModel)
        {
            var model = new AuthenticationViewModel();
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var userName = postModel.Username;
            var password = _passwordHashProvidcer.Hash(postModel.Password, _salt);
            var user = _unitOfWork.UserRepository.GetUserByUsernameAndPassword(userName, password);
            if (user != null)
            {
                FormsAuthentication.SetAuthCookie(user.UserName, false);
                // Not a good practice
                Session[SessionUserKey] = user;
                // Map User to Model
                model = new AuthenticationViewModel()
                {
                    IdHashed = _encryptionProvider.Encrypt(user.Id.ToString(), _key, _vector),
                    Name = user.Name,
                    EMail = user.EMail.SanitizeEmail()
                };
            }
            return View(model);
        }

        private const string SessionCookieNamePrefix = "site__";
        public ActionResult SessionManagement()
        {
            var siteCookie = GetSessionCookie();
            if (siteCookie != null)
            {
                ViewData["session_id"] = siteCookie.Value;
                return View();
            }
            var sessionId = _passwordHashProvidcer.Hash(Guid.NewGuid() + _randomNumberGenerator.GenerateLong().ToString(), _salt);
            var custom = _passwordHashProvidcer.Hash(Guid.NewGuid() + _randomNumberGenerator.Generate().ToString(), _salt);
            var cookieName = string.Format("{0}{1}", SessionCookieNamePrefix, custom);
            var sessionCookie = new HttpCookie(cookieName)
            {
                Value = sessionId,
                Domain = Request.Url.Host,
                Path = "~/good/",
                // Expires = End of the session,
                HttpOnly = true,
                Shareable = false
            };
            Response.Cookies.Add(sessionCookie);
            ViewData["session_id"] = sessionId;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SessionManagement(bool logout)
        {
            if (ModelState.IsValid)
            {
                FormsAuthentication.SignOut();
                Session.Abandon();
                var sc = GetSessionCookie();
                if (sc != null)
                {
                    var removeCookie = new HttpCookie(sc.Name)
                    {
                        Path = "~/good/", // If not same path provided cookie will not be removed
                        Expires = DateTime.Now.AddDays(-1) // To remove cookie: set to expire
                    };
                    Response.Cookies.Add(removeCookie);
                }
                ViewData["session_id"] = "bye bye...";
            }
            else
            {
                ViewData["session_id"] = "You are a terrible lier!";
            }
            return View();
        }

        private HttpCookie GetSessionCookie()
        {
            var key = Request.Cookies.AllKeys.AsQueryable().FirstOrDefault(s => s.StartsWith(SessionCookieNamePrefix));
            if (string.IsNullOrEmpty(key)) key = SessionCookieNamePrefix;
            var cookie = Request.Cookies[key];
            return cookie;
        }

        private const string AccessLevel = "access_level";
        public ActionResult AccessControl()
        {
            ViewData[AccessLevel] = "None";
            if (Session[SessionUserKey] == null) return View();

            // Not a good practice
            var user = (User)Session[SessionUserKey];
            if (user.IsAdmin)
            {
                ViewData[AccessLevel] = "Admin";
            }
            else if (user.IsStaff)
            {
                ViewData[AccessLevel] = "Staff";
            }
            else
            {
                ViewData[AccessLevel] = "User";
            }
            return View();
        }

        public ActionResult CryptographicPractices()
        {
            return View();
        }

        public ActionResult ErrorHandling()
        {
            try
            {
                throw new InvalidOperationException();
            }
            catch (Exception ex)
            {
                _logger.Error("We are handling don't worry", ex);
            }
            return View();
        }


        public ActionResult Logging()
        {
            if (Session[SessionUserKey] != null)
            {
                var user = (User)Session[SessionUserKey];
                _logger.Info(string.Format("{0} called Logging action.", user.UserName));
            }

            _logger.Debug(">> Logging");
            try
            {
                _logger.Debug(">> Try");
                _logger.Info(":: Throwing InvalidOperationException");
                _logger.Debug("<< Try");
                throw new InvalidOperationException();
            }
            catch (Exception ex)
            {
                ViewData["incident_id"] = _encryptionProvider.Encrypt(Guid.NewGuid().ToString() + _randomNumberGenerator.Generate(), _key, _vector);
                _logger.Debug(">> Catch");
                _logger.Error("Log Everything", ex);
                _logger.Debug("<< Catch");
            }
            _logger.Debug("<< Logging");
            return View();
        }

        public ActionResult DataProtection()
        {
            return View();
        }

        public ActionResult CommunicationSecurity()
        {
            return View();
        }

        public ActionResult FileManagement()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult FileManagement(HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                if (upload != null && upload.ContentLength > 0)
                {
                    var fileName = Guid.NewGuid() + "__" + Path.GetFileName(upload.FileName);
                    var path = Path.Combine(Server.MapPath("~/App_Data/uploads/temp/"), fileName);
                    upload.SaveAs(path);
                    var fi = new FileInfo(path);
                    // Check File Hader (Magic Number)
                    if (!fi.IsJpeg())
                    {
                        fi.Delete();
                    }

src/SCP.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - .Net SCP</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("SCP", "Index", "Home", new {area = ""}, new {@class = "navbar-brand"})
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
            </ul>
        </div>
    </div>
</div>
<div class="container body-content">
    <h2>Secure Coding Practices</h2>
    <hr/>
    <div class="row">
        <div class="col-md-8">
            <div class="panel panel-default">
                <div class="panel-body">
                    @RenderBody()
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel-group">
                <div class="panel panel-info">
                    <div class="panel panel-heading panel-title">
                        Table of Contents
                    </div>
                    <div class="panel panel-body">
                        <ul>
                            <li>@Html.ActionLink("Index", "Index", "Home")</li>
                            <li>
                                @Html.ActionLink("Bad Examples", "Index", "Bad")
                                <ul>
                                    <li>@Html.ActionLink("Input Validation", "InputValidation", "Bad")</li>
                                    <li>@Html.ActionLink("Output Encoding", "OutputEncoding", "Bad")</li>
                                    <li>@Html.ActionLink("Authentication and Password Management", "Authentication", "Bad")</li>
                                    <li>@Html.ActionLink("Session Management", "SessionManagement", "Bad")</li>
                                    <li>@Html.ActionLink("Access Control", "AccessControl", "Bad")</li>
                                    <li>@Html.ActionLink("Cryptographic Practices", "CryptographicPractices", "Bad")</li>
                                    <li>@Html.ActionLink("Error Handling", "ErrorHandling", "Bad")</li>
                                    <li>@Html.ActionLink("Logging", "Logging", "Bad")</li>
                                    <li>@Html.ActionLink("Data Protection", "DataProtection", "Bad")</li>
                                    <li>@Html.ActionLink("CommunicationSecurity", "CommunicationSecurity", "Bad")</li>
                                    <li>@Html.ActionLink("File Management", "FileManagement", "Bad")</li>
                                    <li>@Html.ActionLink("Memory Management", "MemoryManagement", "Bad")</li>
                                </ul>
                            </li>
                            <li>
                                @Html.ActionLink("Good Examples", "Index", "Good")
                                <ul>
                                    <li>@Html.ActionLink("Input Validation", "InputValidation", "Good")</li>
                                    <li>@Html.ActionLink("Output Encoding", "OutputEncoding", "Good")</li>
                                    <li>@Html.ActionLink("Authentication and Password Management", "Authentication", "Good")</li>
                                    <li>@Html.ActionLink("Session Management", "SessionManagement", "Good")</li>
                                    <li>@Html.ActionLink("Access Control", "AccessControl", "Good")</li>
                                    <li>@Html.ActionLink("Cryptographic Practices", "CryptographicPractices", "Good")</li>
                                    <li>@Html.ActionLink("Error Handling", "ErrorHandling", "Good")</li>
                                    <li>@Html.ActionLink("Logging", "Logging", "Good")</li>
                                    <li>@Html.ActionLink("Data Protection", "DataProtection", "Good")</li>
                                    <li>@Html.ActionLink("CommunicationSecurity", "CommunicationSecurity", "Good")</li>
                                    <li>@Html.ActionLink("File Management", "FileManagement", "Good")</li>
                                    <li>@Html.ActionLink("Memory Management", "MemoryManagement", "Good")</li>
                                </ul>
                            </li>
                            <li>@Html.ActionLink("Database Security", "DatabaseSecurity", "Home")</li>
                            <li>@Html.ActionLink("System Configuration", "SystemConfiguration", "Home")</li>
                            <li>@Html.ActionLink("General Coding Practices", "GeneralCodingPractices", "Home")</li>
                            <li>@Html.ActionLink("How to Design Secure Systems", "HowtoDesignSecureSystems", "Home")</li>
                        </ul>
                    </div>
                </div>
                <div class="panel panel-info">
                    <div class="panel panel-heading panel-title">
                        Resources
                    </div>
                    <div class="panel panel-body">
                        <ul>
                            <li>
                                <a href="https://www.pcisecuritystandards.org/" target="blank" title="Payment Card Industry - Security Standards Council">PCI SSC</a>
                                <ul>
                                    <li>
                                        <a href="https://www.pcisecuritystandards.org/document_library" target="blank">Document Library</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href="https://www.owasp.org/" target="blank">OWASP</a>
                                <ul>
                                    <li>
                                        <a href="https://www.owasp.org/index.php/OWASP_Secure_Coding_Practices_-_Quick_Reference_Guide" target="blank">SCP Quick Reference Guide</a>
                                    </li>
                                    <li>
                                        <a href="https://www.owasp.org/index.php/OWASP_Top_Ten_Cheat_Sheet">Top Ten Cheat Sheet</a>
                                    </li>
                                    <li>
                                        <a href="https://www.owasp.org/index.php/Category:OWASP_Java_Project" target="blank">Java Project</a>
                                    </li>
                                    <li>
                                        <a href="https://www.owasp.org/index.php/.NET" target="blank">.Net Project</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href="https://samate.nist.gov/SRD/index.php" title="NIST Software Assurance Reference Dataset Project" target="blank">US NIST SARD Project</a>
                                <ul>
                                    <li>
                                        <a href="https://samate.nist.gov/SRD/testsuite.php" target="blank">SARD Vulnerability Test Suites</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href="http://cwe.mitre.org/index.html">Common Weakness Enumeration (CWE)</a>
                            </li>
                            <li>
                                <a href="https://www.sans.org/">SANS</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - .NET Secure Coding Practices</p>
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", false)
</body>
</html>